# Generated by Django 3.0.3 on 2020-03-10 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateField(blank=True, null=True, verbose_name='date_of_purchase')),
                ('host_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='host_name')),
                ('inventory_number', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='model')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='serial_number')),
                ('part_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='part_number')),
                ('memory', models.CharField(blank=True, max_length=255, null=True, verbose_name='memory')),
                ('qr_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='qr_id')),
                ('state', models.CharField(blank=True, choices=[('IN_USE', 'IN_USE'), ('SPARE', 'SPARE'), ('BROKEN', 'BROKEN'), ('DISPOSED', 'DISPOSED')], default='SPARE', max_length=255, null=True, verbose_name='state')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('status_inventory', models.IntegerField(blank=True, choices=[(0, 'find me'), (1, 'Found')], default='0', null=True, verbose_name='status_inventory')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Type of Equipment',
                'verbose_name_plural': 'Type of Equipments',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEquipment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_of_purchase', models.DateField(blank=True, null=True, verbose_name='date_of_purchase')),
                ('host_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='host_name')),
                ('inventory_number', models.CharField(db_index=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='model')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='serial_number')),
                ('part_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='part_number')),
                ('memory', models.CharField(blank=True, max_length=255, null=True, verbose_name='memory')),
                ('qr_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='qr_id')),
                ('state', models.CharField(blank=True, choices=[('IN_USE', 'IN_USE'), ('SPARE', 'SPARE'), ('BROKEN', 'BROKEN'), ('DISPOSED', 'DISPOSED')], default='SPARE', max_length=255, null=True, verbose_name='state')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('status_inventory', models.IntegerField(blank=True, choices=[(0, 'find me'), (1, 'Found')], default='0', null=True, verbose_name='status_inventory')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('device_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment.EquipmentType')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_inventory', to='equipment.Equipment')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment.Location')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Equipment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='equipment',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.EquipmentType'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.Location'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
