# Generated by Django 3.0.3 on 2020-02-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LdapConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LDAP_URL', models.CharField(max_length=50)),
                ('LDAP_USER', models.CharField(max_length=30)),
                ('LDAP_PASS', models.CharField(max_length=30)),
                ('LDAP_BASE_DN', models.CharField(max_length=250)),
                ('LDAP_AUTH', models.BooleanField(default='False')),
            ],
        ),
    ]
