# Generated by Django 3.0.3 on 2020-03-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0003_auto_20200310_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodeconfig',
            name='model_font_size',
            field=models.DecimalField(decimal_places=2, default=0.25, max_digits=19),
        ),
    ]
