# Generated by Django 3.0.3 on 2020-03-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0004_qrcodeconfig_model_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodeconfig',
            name='model_visibility',
            field=models.BooleanField(default=False),
        ),
    ]
