# Generated by Django 3.0.3 on 2020-03-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0005_qrcodeconfig_model_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodeconfig',
            name='inventory_margin_top',
            field=models.DecimalField(decimal_places=2, default=-0.25, max_digits=19),
        ),
    ]
